name: manage-azure-policy-f30163be
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/jaytest_cfecf8c2-6dfc-4ef5-afae-c7401b9ba19b/**'
#      - 'policies/jaydisk_d6d718c5-a41d-4bf0-8ccb-3ca6481658f2/**'
#      - .github/workflows/manage-azure-policy-f30163be.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_f30163be}}
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/jaytest_cfecf8c2-6dfc-4ef5-afae-c7401b9ba19b/**
          policies/jaydisk_d6d718c5-a41d-4bf0-8ccb-3ca6481658f2/**
